name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CLIENTS_AMOUNT=5
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
        read_only: true

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Nombre1
      - APELLIDO=Apellido1
      - DOCUMENTO=30904461
      - NACIMIENTO=1999-03-17
      - NUMERO=7571
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Nombre2
      - APELLIDO=Apellido2
      - DOCUMENTO=30904462
      - NACIMIENTO=1999-03-17
      - NUMERO=7572
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Nombre3
      - APELLIDO=Apellido3
      - DOCUMENTO=30904463
      - NACIMIENTO=1999-03-17
      - NUMERO=7573
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Nombre4
      - APELLIDO=Apellido4
      - DOCUMENTO=30904464
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Nombre5
      - APELLIDO=Apellido5
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7575
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
