name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CLIENTS_AMOUNT=5
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
        read_only: true

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ./.data/agency-1.csv
        target: /agency-1.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ./.data/agency-2.csv
        target: /agency-2.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ./.data/agency-3.csv
        target: /agency-3.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ./.data/agency-4.csv
        target: /agency-4.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
        read_only: true
      - type: bind
        source: ./.data/agency-5.csv
        target: /agency-5.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
